import { type CharacterConfig, registerCharacter } from "../characterConfig";
import { calculateGaugeCost, comboVideoAsset, type ComboData } from "../comboData";

/**
 * イングリッド用コンボデータ
 * 実装例：基本的なコンボセット
 */
const ingridCombosRaw: Omit<ComboData, 'driveConsumption' | 'superConsumption'>[] = [
  {
    id: "combo_1",
    number: 1,
    title: "DI壁やられノーゲージ",
    startup: "壁やられ",
    notation: "(W!)DI > 4HP~HP xx 214MP > 236MK",
    damage: 2432,
    knockdown: "+37",
    position: "端",
    difficulty: "易",
    stock: "0",
    description: "ノーゲージで起き攻め投げ+5・中段+6・弾重ね+2ができるルート。",
    videoAsset: comboVideoAsset("ingrid_01", "イングリッド #01 DI壁やられノーゲージ"),
  },
  {
    id: "combo_2",
    number: 2,
    title: "DI壁やられSA3",
    startup: "壁やられ・リーサル",
    notation: "(W!)DI > 4HP~HP xx (OD)214P > 2KKK > (OD)236K xx SA3",
    damage: 4960,
    damageLabel: "4960(5248)",
    knockdown: "+30",
    position: "端",
    difficulty: "難",
    stock: "1(2~)",
    description: "リーサル時に使用。2KKKを6KKKで4984ダメージ。ストック2本以上でも可のため難易度的にも推奨。",
    videoAsset: comboVideoAsset("ingrid_02", "イングリッド #02 DI壁やられSA3"),
  },
  {
    id: "combo_3",
    number: 3,
    title: "DI壁やられSA3節約",
    startup: "壁やられ・リーサル",
    notation: "(W!)DI > 4HP~HP xx (OD)214P > 2KKK > 236LP xx SA3",
    damage: 4896,
    damageLabel: "4896(5184)",
    knockdown: "+30",
    position: "端",
    difficulty: "難",
    stock: "1(2~)",
    description: "リーサル時に使用。ドライブゲージ状況ではこちらになることもあるがSA3つなぎで少しミスしやすい。",
    videoAsset: comboVideoAsset("ingrid_03", "イングリッド #03 DI壁やられSA3節約"),
  },
  {
    id: "combo_4",
    number: 4,
    title: "スタン起き攻め",
    startup: "スタン",
    notation: "(W! STN)DI > 214LP[2] > 4HP~HP xx 214MP > 236MK",
    damage: 2420,
    knockdown: "+37",
    position: "端",
    difficulty: "中",
    stock: "0",
    description: "ストック2貯めつつ起き攻め",
    videoAsset: comboVideoAsset("ingrid_04", "イングリッド #04 スタン起き攻め"),
  },
  {
    id: "combo_5",
    number: 5,
    title: "スタンSA3",
    startup: "スタン・リーサル",
    notation: "(W! STN)DI > 214LP[2] > 6HP xx (OD)214P > 4HP~HP > SA3",
    damage: 4980,
    knockdown: "+30",
    position: "端",
    difficulty: "中",
    stock: "2",
    description: "リーサル時に使用。ドライブゲージ状況次第。",
    videoAsset: comboVideoAsset("ingrid_05", "イングリッド #05 スタンSA3"),
  },
  {
    id: "combo_6",
    number: 6,
    title: "スタン高火力SA3",
    startup: "スタン・リーサル",
    notation: "(W! STN)DI > 214LP[2] > 6HP xx (OD)214P > 4HP~HP > (OD)214P > 2KKK > SA3",
    damage: 5620,
    knockdown: "+30",
    position: "端",
    difficulty: "難",
    stock: "2",
    description: "リーサル時に使用。ドライブゲージがあればここまで伸びる。",
    videoAsset: comboVideoAsset("ingrid_06", "イングリッド #06 スタン高火力SA3"),
  },
  {
    id: "combo_7",
    number: 7,
    title: "スタン低リソースSA3",
    startup: "スタン・リーサル",
    notation: "(W! STN)DI > 214LP[2] > 236HK > j.MP > 214HP > SA3",
    damage: 4275,
    knockdown: "+30",
    position: "端",
    difficulty: "中",
    stock: "0",
    description: "Driveゲージもストックもない時のリーサル時に使用。",
    videoAsset: comboVideoAsset("ingrid_07", "イングリッド #07 スタン低リソースSA3"),
  },
  {
    id: "combo_8",
    number: 8,
    title: "スタンロマンリーサル",
    startup: "スタン・リーサル",
    notation: "(W! STN)DI > 214LP[2] > 6HP xx (OD)214P > 4HP~HP xx (OD)214P > 214LP > (OD)214P > 236HP xx SA3",
    damage: 5879,
    knockdown: "+30",
    position: "端",
    difficulty: "難",
    stock: "4",
    description: "ストック2本時のロマンリーサル。最後236HPはディレイでないとSA3がでない。使用用途はほぼない。",
    videoAsset: comboVideoAsset("ingrid_08", "イングリッド #08 スタンロマンリーサル"),
  },
  {
    id: "combo_9",
    number: 9,
    title: "+37継続起き攻め",
    startup: "セットプレイ",
    notation: "▲2LP > 6MP > 5MP~MK xx 236MK",
    damage: 2480,
    knockdown: "+38",
    position: "端",
    difficulty: "中",
    stock: "0",
    description: "+37から再度起き攻め可能。",
    videoAsset: comboVideoAsset("ingrid_09", "イングリッド #09 +37継続起き攻め"),
  },
  {
    id: "combo_10",
    number: 10,
    title: "+37ラッシュSA1",
    startup: "セットプレイ",
    notation: "▲2LP > 6MP > 5MP~MK xx DRC > 2HP > 236HK > 214HP > DR > 4MK~HP > SA1",
    damage: 3803,
    knockdown: "+12",
    position: "端",
    difficulty: "難",
    stock: "2",
    description: "+37からドライブラッシュでダメージ伸ばし",
    videoAsset: comboVideoAsset("ingrid_10", "イングリッド #10 +37ラッシュSA1"),
  },
  {
    id: "combo_11",
    number: 11,
    title: "+37フレーム消費投げ",
    startup: "セットプレイ",
    notation: "▲2LP > ▲5LK > 投げ",
    damage: 1200,
    knockdown: "+21",
    position: "端",
    difficulty: "易",
    stock: "0",
    description: "+37からフレーム消費後投げ。",
    videoAsset: comboVideoAsset("ingrid_11", "イングリッド #11 +37フレーム消費投げ"),
  },
  {
    id: "combo_12",
    number: 12,
    title: "+37弾重ね継続",
    startup: "セットプレイ",
    notation: "▲5LP > 236LP > 5MP~MK xx 236MK",
    damage: 2270,
    knockdown: "+38",
    position: "端",
    difficulty: "中",
    stock: "0",
    description: "+37から+38のセットプレイが可能",
    videoAsset: comboVideoAsset("ingrid_12", "イングリッド #12 +37弾重ね継続"),
  },
  {
    id: "combo_13",
    number: 13,
    title: "+37弾ガード投げ",
    startup: "セットプレイ",
    notation: "▲5LP > 236LP(ガード) > 投げ",
    damage: 1200,
    knockdown: "+21",
    position: "端",
    difficulty: "易",
    stock: "0",
    description: "+37から持続弾ガード+2からの投げ。",
    videoAsset: comboVideoAsset("ingrid_13", "イングリッド #13 +37弾ガード投げ"),
  },
  {
    id: "combo_14",
    number: 14,
    title: "+37SA1暴れ弾ヒット",
    startup: "セットプレイ",
    notation: "▲5LP > 236LP > 5HK > SA1[2]",
    damage: 3370,
    knockdown: "+20",
    position: "端",
    difficulty: "中",
    stock: "2",
    description: "+37からSA1暴れ弾ヒット+10からの展開。",
    videoAsset: comboVideoAsset("ingrid_14", "イングリッド #14 +37SA1暴れ弾ヒット"),
  },
  {
    id: "combo_15",
    number: 15,
    title: "+37弾ガードリーサル",
    startup: "セットプレイ・リーサル・温存",
    notation: "▲5LP > 236LP(ガード) > 2MP > 2MP > (OD)236K xx SA2[2] > 2HP xx 236MK > 214LP[2] > SA1[2]",
    damage: 5090,
    knockdown: "+20",
    position: "端",
    difficulty: "難",
    stock: "2",
    description: "+37から持続弾ガード+2投げ暴れ潰しからリーサル狙い",
    videoAsset: comboVideoAsset("ingrid_15", "イングリッド #15 +37弾ガードリーサル"),
  },
  {
    id: "combo_16",
    number: 16,
    title: "PC DI安全跳び",
    startup: "(PC)DI",
    notation: "(PC)DI > j.HP > DR > MP~MK xx 236MK",
    damage: 2719,
    knockdown: "+42",
    position: "どこでも",
    difficulty: "中",
    stock: "0",
    description: "安全跳び両起き上がり対応。否リーサル時はこれがメイン。",
    videoAsset: comboVideoAsset("ingrid_16", "イングリッド #16 PC DI安全跳び"),
  },
  {
    id: "combo_17",
    number: 17,
    title: "PC DIリーサル",
    startup: "(PC)DI・リーサル",
    notation: "(PC)DI > 2HP xx DRC > 2HP xx 236HK > (OD)j.214P > SA3",
    damage: 5194,
    knockdown: "+30",
    position: "どこでも",
    difficulty: "難",
    stock: "1",
    description: "リーサル用。最後jMPに変更でストック0で4939ダメージ。",
    videoAsset: comboVideoAsset("ingrid_17", "イングリッド #17 PC DIリーサル"),
  },
  {
    id: "combo_18",
    number: 18,
    title: "PC DI高火力リーサル",
    startup: "(PC)DI・リーサル",
    notation: "(PC)DI > 6HP xx (OD)214P > DR > 2HP xx 236HK > (OD)j.214P > SA3",
    damage: 6084,
    knockdown: "+30",
    position: "どこでも",
    difficulty: "難",
    stock: "3",
    description: "ストック次第の高火力リーサル。",
    videoAsset: comboVideoAsset("ingrid_18", "イングリッド #18 PC DI高火力リーサル"),
  },
  {
    id: "combo_19",
    number: 19,
    title: "PC DIストック回収",
    startup: "(PC)DI",
    notation: "(PC)DI > 66 > 4HP~HP > 214MP",
    damage: 2700,
    knockdown: "+54",
    position: "どこでも",
    difficulty: "易",
    stock: "0",
    description: "ストックを貯めたい場合。最後にキャンセルSA3でリーサル用としても4700ダメージ",
    videoAsset: comboVideoAsset("ingrid_19", "イングリッド #19 PC DIストック回収"),
  },
  {
    id: "combo_20",
    number: 20,
    title: "PC 5HP本命差し返し",
    startup: "差し返し",
    notation: "(PC)5HP > DR > 2HP xx 236HK > j.214LP",
    damage: 2391,
    knockdown: "+25",
    position: "どこでも",
    difficulty: "中",
    stock: "0",
    description: "本命ルート。前ダッシュで+5投げ間合い。最後j.214MP等でリーサルルートにもなる。",
    videoAsset: comboVideoAsset("ingrid_20", "イングリッド #20 PC 5HP本命差し返し"),
  },
  {
    id: "combo_21",
    number: 21,
    title: "PC 5HP定番起き攻め",
    startup: "差し返し",
    notation: "(PC)5HP > DR > 5HK > 5MP~MK xx 236MK",
    damage: 2743,
    knockdown: "+38",
    position: "どこでも",
    difficulty: "中",
    stock: "0",
    description: "差し返しから定番起き攻めルート。5MP~MK後SA2に繋ぐ事も可能。",
    videoAsset: comboVideoAsset("ingrid_21", "イングリッド #21 PC 5HP定番起き攻め"),
  },
  {
    id: "combo_22",
    number: 22,
    title: "PC 5HPノーゲージ",
    startup: "差し返し・温存",
    notation: "(PC)5HP > 6HP xx 214MP",
    damage: 2430,
    knockdown: "+38",
    position: "どこでも",
    difficulty: "中",
    stock: "0",
    description: "ノーゲージの場合選択ルート。",
    videoAsset: comboVideoAsset("ingrid_22", "イングリッド #22 PC 5HPノーゲージ"),
  },
  {
    id: "combo_23",
    number: 23,
    title: "PC 5HPストック確認",
    startup: "差し返し",
    notation: "(PC)5HP > 2HP xx (OD)214P > 66 > 236HK > j.214LP",
    damage: 3630,
    knockdown: "+24",
    position: "どこでも",
    difficulty: "難",
    stock: "2",
    description: "(PC)後に微歩き・ストック確認と難度高いが強力。前ダッシュで+4投げ間合。",
    videoAsset: comboVideoAsset("ingrid_23", "イングリッド #23 PC 5HPストック確認"),
  },
  {
    id: "combo_24",
    number: 24,
    title: "端SA2入れ替え",
    startup: "入れ替え",
    notation: "2MK xx SA2[HP] > 5MP~MK > 236LP > 9j. xx 214LP > 214HK > j.236LP",
    damage: 2890,
    knockdown: "+24",
    position: "端",
    difficulty: "中",
    stock: "0",
    description: "画面端SA2入れ替えルート。前ダッシュで+4投げ間合い。",
    videoAsset: comboVideoAsset("ingrid_24", "イングリッド #24 端SA2入れ替え"),
  },
  {
    id: "combo_25",
    number: 25,
    title: "DR下段起き攻め",
    startup: "起き攻め",
    notation: "DR > 2LK > 5MP~MK xx 236LK",
    damage: 1670,
    knockdown: "+36",
    position: "どこでも",
    difficulty: "中",
    stock: "0",
    description: "前ダッシュ5HK持続当て+6（展開は動画参照）",
    videoAsset: comboVideoAsset("ingrid_25", "イングリッド #25 DR下段起き攻め"),
  },
  {
    id: "combo_26",
    number: 26,
    title: "5MP連携起き攻め",
    startup: "起き攻め・温存",
    notation: "5MP~MK xx 236MK",
    damage: 2140,
    knockdown: "+38",
    position: "どこでも",
    difficulty: "易",
    stock: "0",
    description: "5MP~MK後ガードで236HPでスキを最小限へ（インパクト返し可）",
    videoAsset: comboVideoAsset("ingrid_26", "イングリッド #26 5MP連携起き攻め"),
  },
  {
    id: "combo_27",
    number: 27,
    title: "近距離DR下段崩し",
    startup: "起き攻め",
    notation: "DR > 2LK > 5MP~MK xx 236MK",
    damage: 1770,
    knockdown: "+38",
    position: "どこでも",
    difficulty: "中",
    stock: "0",
    description: "近距離DR下段崩し択",
    videoAsset: comboVideoAsset("ingrid_27", "イングリッド #27 近距離DR下段崩し"),
  },
  {
    id: "combo_28",
    number: 28,
    title: "遠めDR中段崩し",
    startup: "起き攻め",
    notation: "DR > 4MK > 2MK xx 236MK",
    damage: 2160,
    knockdown: "+21",
    position: "どこでも",
    difficulty: "中",
    stock: "0",
    description: "遠めからのDRで少しめり込めば2MKがヒット",
    videoAsset: comboVideoAsset("ingrid_28", "イングリッド #28 遠めDR中段崩し"),
  },
  {
    id: "combo_29",
    number: 29,
    title: "+38投げ択",
    startup: "セットプレイ",
    notation: "66 > 微歩き投げ",
    damage: 1200,
    knockdown: "+21",
    position: "どこでも",
    difficulty: "易",
    stock: "0",
    description: "+38からの投げ択",
    videoAsset: comboVideoAsset("ingrid_29", "イングリッド #29 +38投げ択"),
  },
  {
    id: "combo_30",
    number: 30,
    title: "+38投げ読み択",
    startup: "セットプレイ",
    notation: "(PC)5HP > DR > 5HK > 5MP~MK xx 236MK",
    damage: 2743,
    knockdown: "+38",
    position: "どこでも",
    difficulty: "中",
    stock: "0",
    description: "+38からの投げ読み択",
    videoAsset: comboVideoAsset("ingrid_30", "イングリッド #30 +38投げ読み択"),
  },
  {
    id: "combo_31",
    number: 31,
    title: "+38遅らせ読み",
    startup: "セットプレイ",
    notation: "66 > (CH)5HK > 5MP~MK xx 236MK",
    damage: 2840,
    knockdown: "+38",
    position: "どこでも",
    difficulty: "中",
    stock: "0",
    description: "+38からの遅らせ（投げ・打撃）読み。ノーマルヒットは5LP > MK xx 236MKへ",
    videoAsset: comboVideoAsset("ingrid_31", "イングリッド #31 +38遅らせ読み"),
  },
  {
    id: "combo_32",
    number: 32,
    title: "先端連携カバー",
    startup: "セットプレイ",
    notation: "5MP~MK xx 236HP(ガード)",
    damage: 0,
    knockdown: "-3",
    position: "どこでも",
    difficulty: "易",
    stock: "0",
    description: "先端MP〜MKなら236HPでカバーで-3（インパクト返せる）",
    videoAsset: comboVideoAsset("ingrid_32", "イングリッド #32 先端連携カバー"),
  },
  {
    id: "combo_33",
    number: 33,
    title: "サンフレアLv2単独",
    startup: "その他・温存",
    notation: "214HP[2] > 6KKK",
    damage: 2050,
    knockdown: "+47",
    position: "どこでも",
    difficulty: "易",
    stock: "2",
    description: "サンフレアLv2単独ヒット時の用途",
    videoAsset: comboVideoAsset("ingrid_33", "イングリッド #33 サンフレアLv2単独"),
  },
  {
    id: "combo_34",
    number: 34,
    title: "サンフレアLv3起き攻め",
    startup: "その他",
    notation: "(OD)214HP[2] > 2KKK > 236MK",
    damage: 3170,
    knockdown: "+38",
    position: "どこでも",
    difficulty: "中",
    stock: "2",
    description: "サンフレアLv3単独ヒット時の用途",
    videoAsset: comboVideoAsset("ingrid_34", "イングリッド #34 サンフレアLv3起き攻め"),
  },
  {
    id: "combo_35",
    number: 35,
    title: "サンフレアLv3SA1伸ばし",
    startup: "その他",
    notation: "(OD)214HP[2] > 2KKK > 5HK xx SA1",
    damage: 3530,
    knockdown: "+12",
    position: "どこでも",
    difficulty: "中",
    stock: "2",
    description: "サンフレアLv3単独ヒット時のSA1伸ばし",
    videoAsset: comboVideoAsset("ingrid_35", "イングリッド #35 サンフレアLv3SA1伸ばし"),
  },
  {
    id: "combo_36",
    number: 36,
    title: "サンフレアLv3SA3伸ばし",
    startup: "その他・リーサル",
    notation: "(OD)214HP[2] > 2KKK > (OD)236K xx SA3",
    damage: 5020,
    knockdown: "+30",
    position: "どこでも",
    difficulty: "難",
    stock: "2",
    description: "サンフレアLv3単独ヒット時のSA3伸ばし",
    videoAsset: comboVideoAsset("ingrid_36", "イングリッド #36 サンフレアLv3SA3伸ばし"),
  },
  {
    id: "combo_37",
    number: 37,
    title: "お手軽リーサル",
    startup: "その他・リーサル",
    notation: "6HP > (OD)214HP[2] > SA3",
    damage: 5696,
    knockdown: "+30",
    position: "どこでも",
    difficulty: "中",
    stock: "2",
    description: "イングリッドお手軽リーサル",
    videoAsset: comboVideoAsset("ingrid_37", "イングリッド #37 お手軽リーサル"),
  },
];

// 計算結果をコンボデータに追加
const ingridCombos: ComboData[] = ingridCombosRaw.map((combo) => {
  const calculation = calculateGaugeCost(combo.notation);
  return {
    ...combo,
    driveConsumption: calculation.driveConsumption,
    superConsumption: calculation.superConsumption,
    driveGaugeCost: calculation.driveGaugeCost,
  } as ComboData;
});

const ingridConfig: CharacterConfig = {
  id: "ingrid",
  name: "Ingrid",
  nameJp: "イングリッド",
  title: "INGRID COMBO DESK",
  subtitle: "2026年版",
  seoTitle: "SF6 イングリッド コンボ集｜ストック・起き攻め・リーサル検索",
  seoDescription:
    "SF6 イングリッドのコンボ集。ストック・起き攻め・リーサルを検索できます。",
  beginnerComboIds: [34, 26, 37],
  beginnerSteps: [
    {
      comboId: 34,
      filterPurpose: "その他",
      note: "サンフレア（214HP）Lv2・Lv3ヒット時の状況を覚えコンボにつなげることにより勝ち筋が近くなる",
    },
    {
      comboId: 26,
      filterPurpose: "起き攻め",
      note: "MP~MKのターゲットコンボから起き攻めのバリエーションを覚え相手を翻弄する",
    },
    {
      comboId: 37,
      filterPurpose: "リーサル",
      note: "スタン・壁やられ・インパクト後・サンフレアヒット後などリーサルが確定する状況を理解する",
    },
  ],

  colors: {
    primary: "#3b82f6",      // 青
    accent: "#f59e0b",       // 琥珀
    background: "linear-gradient(135deg, #0a0e27 0%, #1a1f3a 50%, #0d1117 100%)",
  },

  description:
    "イングリッドの実用コンボを始動・位置・ゲージ消費・起き攻め有利で比較できるレポートです。",

  comboTheory:
    "サンシンボル（ストック）を着実に貯め、サンフレア（214HP）Lv2・Lv3ヒット時の状況やエアリートス（5MP~MK）のターゲットコンボからの攻防など基本コンボから高火力ルートまで、状況に応じた選択肢を用意することが重要。",

  comboTheoryDetail:
    "イングリッドは多彩な択一攻撃とゲージ管理が特徴のキャラクター。基本的な確認コンボから高火力ルートまで、各状況に応じた最適なコンボ選択が勝利につながります。",

  patchFindings: [
    {
      date: "2026-03-17",
      change: "イングリッド調整内容確認中",
      comboImpact: "最新パッチ情報を追加予定",
      confidence: "中",
    },
  ],

  combos: ingridCombos,

  filterOptions: {
    positions: ["すべて", "どこでも", "端", "端付近"],
    purposes: [
      "すべて",
      "温存",
      "起き攻め",
      "運び",
      "リーサル",
      "差し返し",
      "セットプレイ",
      "(PC)DI",
      "壁やられ",
      "スタン",
      "その他",
    ],
    situationTags: [
      "温存",
      "起き攻め",
      "運び",
      "リーサル",
      "差し返し",
      "セットプレイ",
      "(PC)DI",
      "壁やられ",
      "スタン",
      "その他",
    ],
  },
};

// イングリッドを登録
registerCharacter(ingridConfig);

export default ingridConfig;
