import { type CharacterConfig, registerCharacter } from "../characterConfig";
import { calculateGaugeCost, comboVideoAsset, type ComboData } from "../comboData";

const yasmineCombosRaw: Omit<ComboData, "driveConsumption" | "superConsumption">[] = [
  {
    id: "combo_1",
    number: 1,
    title: "PC DI入れ替え",
    startup: "その他",
    notation: "(PC)DI > 236LK~P > 5HP xx 421HK",
    damage: 2660,
    knockdown: "+19",
    position: "端付近",
    difficulty: "易",
    description: "インパクト返し・無敵など入れ替えコンボ",
    situationTags: ["その他"],
    videoAsset: comboVideoAsset("yasmine_01", "ヤスミン #01 PC DI入れ替え"),
  },
  {
    id: "combo_2",
    number: 2,
    title: "PC DI運び",
    startup: "(PC)DI",
    notation: "(PC)DI > jHK >  DR > 2MP xx 214HP > 5HP xx 623HK",
    damage: 3175,
    knockdown: "+19",
    position: "どこでも",
    difficulty: "中",
    description: "インパクト返し運び・ダメージも含めリーサル以外はこれでOK",
    situationTags: ["(PC)DI", "運び"],
    videoAsset: comboVideoAsset("yasmine_02", "ヤスミン #02 PC DI運び"),
  },
  {
    id: "combo_3",
    number: 3,
    title: "大K差し返し",
    startup: "差し返し",
    notation: "(PC)HK >  DR > 2MP xx 214HP > 5HP xx 623HK",
    damage: 2535,
    knockdown: "+19",
    position: "どこでも",
    difficulty: "中",
    description: "大Kカウンター時は運び・ダメージとこれが安定",
    situationTags: ["差し返し", "運び"],
    videoAsset: comboVideoAsset("yasmine_03", "ヤスミン #03 大K差し返し"),
  },
  {
    id: "combo_4",
    number: 4,
    title: "DI壁やられノーゲージ",
    startup: "壁やられ",
    notation: "(W!)DI > 2HP xx 214MP > 5HP xx 623HK",
    damage: 2501,
    knockdown: "+19",
    position: "端付近",
    difficulty: "易",
    description: "ノーゲージお手軽コンボ",
    situationTags: ["壁やられ"],
    videoAsset: comboVideoAsset("yasmine_04", "ヤスミン #04 DI壁やられノーゲージ"),
  },
  {
    id: "combo_5",
    number: 5,
    title: "壁スタン汎用",
    startup: "スタン",
    notation: "(W! STN)DI > 66 > 7j > 22HP > 5HK > 214HP > 5HP xx 623HK",
    damage: 2410,
    knockdown: "+19",
    position: "端付近",
    difficulty: "中",
    description: "壁スタンであればどこからでもOK",
    situationTags: ["スタン"],
    videoAsset: comboVideoAsset("yasmine_05", "ヤスミン #05 壁スタン汎用"),
  },
  {
    id: "combo_6",
    number: 6,
    title: "下段DRC起き攻め",
    startup: "起き攻め",
    notation: "2MK xx  DRC > 2MP > 2HP xx 214MP",
    damage: 1941,
    knockdown: "+2",
    position: "どこでも",
    difficulty: "中",
    description: "バヤニ・モードを溜めて攻め継続・投げorシミーが可能",
    situationTags: ["起き攻め"],
    videoAsset: comboVideoAsset("yasmine_06", "ヤスミン #06 下段DRC起き攻め"),
  },
  {
    id: "combo_7",
    number: 7,
    title: "シミー後セットプレイ",
    startup: "セットプレイ",
    notation: "2MP > 2HP xx 236HP~6P >  DR > 2MP xx 214HP > 5HP xx 623HK",
    damage: 3659,
    knockdown: "+19",
    position: "どこでも",
    difficulty: "中",
    description: "#6のシミー後に狙うコンボの一例",
    situationTags: ["セットプレイ"],
    videoAsset: comboVideoAsset("yasmine_07", "ヤスミン #07 シミー後セットプレイ"),
  },
  {
    id: "combo_8",
    number: 8,
    title: "+38持続当て",
    startup: "起き攻め",
    notation: "2MK xx  DRC > 2MP > 5MP~MP xx 236MP~6MP",
    damage: 1752,
    knockdown: "+38",
    position: "どこでも",
    difficulty: "中",
    description: "バヤニ・モードを溜めて攻め継続。5LPフレーム消費6MPで持続当て+5　関連#23",
    situationTags: ["起き攻め"],
    videoAsset: comboVideoAsset("yasmine_08", "ヤスミン #08 +38持続当て"),
  },
  {
    id: "combo_9",
    number: 9,
    title: "+43密着起き攻め",
    startup: "起き攻め",
    notation: "DR > 2MP > 2HP xx (OD)22PP > LK > 22HP > 2HK > 214MP",
    damage: 2910,
    knockdown: "+43",
    position: "どこでも",
    difficulty: "中",
    description: "バヤニ・モードを溜めて攻め継続。前ダッシュx2で+5密着",
    situationTags: ["起き攻め"],
    videoAsset: comboVideoAsset("yasmine_09", "ヤスミン #09 +43密着起き攻め"),
  },
  {
    id: "combo_10",
    number: 10,
    title: "壁スタンノーゲージ最大",
    startup: "スタン",
    notation: "(W! STN)DI > 44 > 44 > 66 > 8jHK > 2HP xx 22HP > 2MP > 214HP > 5HP xx 623HK",
    damage: 2510,
    knockdown: "+20",
    position: "端付近",
    difficulty: "難",
    description: "密着時の壁スタン後ノーゲージ最大",
    situationTags: ["スタン"],
    videoAsset: comboVideoAsset("yasmine_10", "ヤスミン #10 壁スタンノーゲージ最大"),
  },
  {
    id: "combo_11",
    number: 11,
    title: "マニアック入れ替え",
    startup: "入れ替え",
    notation: "DR > (PC)5HP > 2HP xx 22LP > LK > 22HP > 5HP > 66 > 421HK",
    damage: 3100,
    knockdown: "+19",
    position: "端付近",
    difficulty: "難",
    description: "マニアックな入れ替えコンボ",
    situationTags: ["その他"],
    videoAsset: comboVideoAsset("yasmine_11", "ヤスミン #11 マニアック入れ替え"),
  },
  {
    id: "combo_12",
    number: 12,
    title: "PC 5HP運び",
    startup: "運び",
    notation: "DR > (PC)5HP > 2HP xx 22LP > LK xx 214HP > 5HP xx 623HK",
    damage: 3510,
    knockdown: "+20",
    position: "どこでも",
    difficulty: "中",
    description: "SAやOD昇龍などガード時に選択するコンボ",
    situationTags: ["運び"],
    videoAsset: comboVideoAsset("yasmine_12", "ヤスミン #12 PC 5HP運び"),
  },
  {
    id: "combo_13",
    number: 13,
    title: "端PC 2HP高火力",
    startup: "その他",
    notation: "DR > (PC)2HP > 2HP xx 22MP > 2MP xx 214HP > 5HP xx 623HK",
    damage: 3690,
    knockdown: "+19",
    position: "端",
    difficulty: "難",
    description: "#12よりもダメージ増。意識が高い人向け。",
    situationTags: ["その他"],
    videoAsset: comboVideoAsset("yasmine_13", "ヤスミン #13 端PC 2HP高火力"),
  },
  {
    id: "combo_14",
    number: 14,
    title: "端ODリーサル",
    startup: "その他・リーサル",
    notation: "DR > (PC)5HP > 5HP xx (OD)22LPHP > 2MP > 8jMP > 214MP > 5HP xx 623HK",
    damage: 3900,
    knockdown: "+19",
    position: "端",
    difficulty: "難",
    description: "#13よりもダメージ増。意識が高い人向け。",
    situationTags: ["その他", "リーサル"],
    videoAsset: comboVideoAsset("yasmine_14", "ヤスミン #14 端ODリーサル"),
  },
  {
    id: "combo_15",
    number: 15,
    title: "下段DR密着攻め",
    startup: "起き攻め",
    notation: "DR > 2LK > 2MP xx 214MP",
    damage: 1450,
    knockdown: "+2",
    position: "どこでも",
    difficulty: "易",
    description: "下段からの密着攻め持続用",
    situationTags: ["起き攻め"],
    videoAsset: comboVideoAsset("yasmine_15", "ヤスミン #15 下段DR密着攻め"),
  },
  {
    id: "combo_16",
    number: 16,
    title: "中攻撃DR密着攻め",
    startup: "起き攻め",
    notation: "DR > 2MP > 2HP xx 214MP",
    damage: 2280,
    knockdown: "+2",
    position: "どこでも",
    difficulty: "易",
    description: "攻めの起点からの密着攻め持続用",
    situationTags: ["起き攻め"],
    videoAsset: comboVideoAsset("yasmine_16", "ヤスミン #16 中攻撃DR密着攻め"),
  },
  {
    id: "combo_17",
    number: 17,
    title: "バヤニ基本運び",
    startup: "運び",
    notation: "DR > 2MP > 2HP xx 236HP~6P > DR > 2MP xx 214HP > 5HP xx 623HK",
    damage: 3479,
    knockdown: "+19",
    position: "どこでも",
    difficulty: "中",
    stock: "あり",
    description: "バヤニ・モード時の基本コンボ。画面端付近の場合途中2HP xx 214MPに変更でダメージ増",
    situationTags: ["運び"],
    videoAsset: comboVideoAsset("yasmine_17", "ヤスミン #17 バヤニ基本運び"),
  },
  {
    id: "combo_18",
    number: 18,
    title: "下段バヤニ基本運び",
    startup: "運び",
    notation: "DR > 2LK > 2MP xx 236HP~6P > DR > 2MP xx 214HP > 5HP xx 623HK",
    damage: 2360,
    knockdown: "+19",
    position: "どこでも",
    difficulty: "中",
    stock: "あり",
    description: "下段始動バヤニ・モード時の基本コンボ。画面端付近の場合途中2HP xx 214MPに変更でダメージ増",
    situationTags: ["運び"],
    videoAsset: comboVideoAsset("yasmine_18", "ヤスミン #18 下段バヤニ基本運び"),
  },
  {
    id: "combo_19",
    number: 19,
    title: "バヤニSA2高火力",
    startup: "リーサル",
    notation: "DR > 2MP > 2HP xx (OD)236PP~6P xx SA2 > 214HP > (OD)236PP~6P",
    damage: 4780,
    knockdown: "+47",
    position: "どこでも",
    difficulty: "難",
    stock: "あり",
    description: "バヤニ・モードSA2高火力コンボ。",
    situationTags: ["リーサル"],
    videoAsset: comboVideoAsset("yasmine_19", "ヤスミン #19 バヤニSA2高火力"),
  },
  {
    id: "combo_20",
    number: 20,
    title: "端空中5HP投げ",
    startup: "セットプレイ",
    notation: "（空中） > 5HP xx 22MP > 投げ",
    damage: 1200,
    knockdown: "+29",
    position: "端",
    difficulty: "易",
    stock: "あり",
    description: "#17#18他、画面端で空中5HP後の起き攻め重視はこれ",
    situationTags: ["セットプレイ"],
    videoAsset: comboVideoAsset("yasmine_20", "ヤスミン #20 端空中5HP投げ"),
  },
  {
    id: "combo_21",
    number: 21,
    title: "端空中5HP SA3",
    startup: "セットプレイ",
    notation: "（空中） > 5HP xx 22MP > 2MP xx 236LP > 5HP xx (OD)236PP~6P > SA3",
    damage: 4640,
    knockdown: "+42",
    position: "端",
    difficulty: "難",
    stock: "あり",
    description: "#17#18他、画面端で空中5HP後の起き攻め（2MPヒット時のレシピ）",
    situationTags: ["セットプレイ"],
    videoAsset: comboVideoAsset("yasmine_21", "ヤスミン #21 端空中5HP SA3"),
  },
  {
    id: "combo_22",
    number: 22,
    title: "端空中5HP二段ヒット",
    startup: "セットプレイ",
    notation: "（空中） > 5HP xx 22MP > 2MP xx 236LP > 2MP xx 236HP~P >  DR > 2HP xx 214MP > 5HP xx 623HK",
    damage: 3322,
    knockdown: "+19",
    position: "端",
    difficulty: "難",
    stock: "あり",
    description: "#17#18他、画面端で空中5HP後の起き攻め（2回目2MPヒット時のレシピ）",
    situationTags: ["セットプレイ"],
    videoAsset: comboVideoAsset("yasmine_22", "ヤスミン #22 端空中5HP二段ヒット"),
  },
  {
    id: "combo_23",
    number: 23,
    title: "#08後ノーバヤニ",
    startup: "セットプレイ",
    notation: "▲5LP > 6MP > 5LK xx 623HK",
    damage: 1940,
    knockdown: "+21",
    position: "どこでも",
    difficulty: "中",
    description: "#08後のセットプレイ。弱ダロイも可能だがバヤニを使わない選択がベター",
    situationTags: ["セットプレイ"],
    videoAsset: comboVideoAsset("yasmine_23", "ヤスミン #23 #08後ノーバヤニ"),
  },
  {
    id: "combo_24",
    number: 24,
    title: "PC DI温存",
    startup: "(PC)DI・温存",
    notation: "(PC)DI > 214HP > 5HP xx 623HK",
    damage: 2980,
    knockdown: "+19",
    position: "どこでも",
    difficulty: "易",
    description: "ドライブゲージ温存用。ゲージがあれば運べる#02を選択したい",
    situationTags: ["(PC)DI", "温存"],
    videoAsset: comboVideoAsset("yasmine_24", "ヤスミン #24 PC DI温存"),
  },
  {
    id: "combo_25",
    number: 25,
    title: "TC持続セットプレイ",
    startup: "セットプレイ",
    notation: "5MK~MK~HK (> DR > 6MP > 2HP xx (OD)22PP > LK > 22HP > 2HK > 214MP)",
    damage: 1500,
    damageLabel: "1500(+2910)",
    knockdown: "+33",
    position: "どこでも",
    difficulty: "難",
    description: "#26同様ターゲットコンボヒット時にDRから6MPが持続ヒットで2HPが繋がる連携例",
    situationTags: ["セットプレイ"],
    videoAsset: comboVideoAsset("yasmine_25", "ヤスミン #25 TC持続セットプレイ"),
  },
  {
    id: "combo_26",
    number: 26,
    title: "TC持続バヤニ連携",
    startup: "セットプレイ",
    notation: "5MP~MP xx 236LP~6P (>  DR > 6MP > 2HP xx 236HP~6P >  DR > 2MP xx 214HP > 5HP xx 623HK)",
    damage: 1700,
    damageLabel: "1700(+3479)",
    knockdown: "+33",
    position: "どこでも",
    difficulty: "難",
    description: "#25同様ターゲットコンボヒット時にDRから6MPが持続ヒットで2HPが繋がる連携例",
    situationTags: ["セットプレイ"],
    videoAsset: comboVideoAsset("yasmine_26", "ヤスミン #26 TC持続バヤニ連携"),
  },
  {
    id: "combo_27",
    number: 27,
    title: "端TCガード後連携",
    startup: "セットプレイ",
    notation: "5MP~MP xx 236LP~6P (>  DR > 6MP > 5MP > 2MP xx 236HP~6P >  DR > 2MP xx 214HP > 5HP xx 623HK)",
    damage: 1700,
    damageLabel: "1700(+3039)",
    knockdown: "+33",
    position: "端",
    difficulty: "難",
    description: "#26の中段がガードされた時は5MPにすることで+4フレ暴れされても相打ちから2MPが繋がる連携例",
    situationTags: ["セットプレイ"],
    videoAsset: comboVideoAsset("yasmine_27", "ヤスミン #27 端TCガード後連携"),
  },
  {
    id: "combo_28",
    number: 28,
    title: "+19起き攻め5LP",
    startup: "セットプレイ",
    notation: "▲5LK > 5LP > 2MP xx 236HP~6P >  DR > 2HP xx 214MP > 5HP xx 22MP",
    damage: 2290,
    knockdown: "+2",
    position: "端",
    difficulty: "難",
    stock: "あり",
    description: "+19から起き攻め5LPがヒット時の例",
    situationTags: ["セットプレイ"],
    videoAsset: comboVideoAsset("yasmine_28", "ヤスミン #28 +19起き攻め5LP"),
  },
  {
    id: "combo_29",
    number: 29,
    title: "+19暴れ潰し2LP",
    startup: "セットプレイ",
    notation: "【▲5LK > 5LP >】 (CH)2LP > 2MP xx 236HP~6P >  DR > 2HP xx 214MP > 5HP xx 22MP",
    damage: 2350,
    knockdown: "+2",
    position: "端",
    difficulty: "難",
    description: "+19から起き攻め5LPガード確認後に(CH)2LPで打撃潰し後の例",
    situationTags: ["セットプレイ"],
    videoAsset: comboVideoAsset("yasmine_29", "ヤスミン #29 +19暴れ潰し2LP"),
  },
  {
    id: "combo_30",
    number: 30,
    title: "+19 5LP連携",
    startup: "セットプレイ",
    notation: "【▲5LK > 5LP > 2LP >】 (CH)5LP~LP > 623HK",
    damage: 1590,
    knockdown: "+21",
    position: "端",
    difficulty: "中",
    description: "+19から起き攻め5LP~LPがヒット時の例",
    situationTags: ["セットプレイ"],
    videoAsset: comboVideoAsset("yasmine_30", "ヤスミン #30 +19 5LP連携"),
  },
  {
    id: "combo_31",
    number: 31,
    title: "+19 LP入れ込み",
    startup: "セットプレイ",
    notation: "【▲5LK > 5LP > 2LP > 5LP~】(CH)LP > 236MP~6P > 623MK",
    damage: 2160,
    knockdown: "+19",
    position: "端",
    difficulty: "難",
    stock: "あり",
    description: "+19から起き攻めLP時にヒット例。ここでの確認は不能な為入れ込み推奨。",
    situationTags: ["セットプレイ"],
    videoAsset: comboVideoAsset("yasmine_31", "ヤスミン #31 +19 LP入れ込み"),
  },
  {
    id: "combo_32",
    number: 32,
    title: "+19 236MPヒット",
    startup: "セットプレイ",
    notation: "【▲5LK > 5LP > 2LP > 5LP~LP > 】(CH)236MP~6P > 623MK",
    damage: 2020,
    knockdown: "+19",
    position: "端",
    difficulty: "難",
    stock: "あり",
    description: "+19から起き攻め236MP時にヒット例。",
    situationTags: ["セットプレイ"],
    videoAsset: comboVideoAsset("yasmine_32", "ヤスミン #32 +19 236MPヒット"),
  },
  {
    id: "combo_33",
    number: 33,
    title: "+19削り連携",
    startup: "セットプレイ",
    notation: "【▲5LK > 5LP > 2LP > 5LP~LP > 236MP~6P】",
    damage: 0,
    knockdown: "-2",
    position: "端",
    difficulty: "中",
    stock: "あり",
    description: "+19から起き攻め5LP~236MPの間でどこで暴れられてもヒットする連携。全ガードでも相手のドライブゲージ1本以上削る",
    situationTags: ["セットプレイ"],
    videoAsset: comboVideoAsset("yasmine_33", "ヤスミン #33 +19削り連携"),
  },
  {
    id: "combo_34",
    number: 34,
    title: "+19投げ",
    startup: "セットプレイ",
    notation: "▲2LP > 投げ",
    damage: 1200,
    knockdown: "+29",
    position: "端",
    difficulty: "易",
    description: "+19から起き攻め▲2LP（+5）からの投げ",
    situationTags: ["セットプレイ"],
    videoAsset: comboVideoAsset("yasmine_34", "ヤスミン #34 +19投げ"),
  },
  {
    id: "combo_35",
    number: 35,
    title: "5HP止め中段",
    startup: "セットプレイ",
    notation: "5HP > ▲3LP > 6MP > 2LP > 5LP~LP > 623HK",
    damage: 2701,
    knockdown: "+21",
    position: "端",
    difficulty: "難",
    description: "+19にせず5HPで止めからの中段セットプレイ例。（あえて▲2LPではなく▲3LPと記載は次の6MPのコマンド化を防ぐ為）",
    situationTags: ["セットプレイ"],
    videoAsset: comboVideoAsset("yasmine_35", "ヤスミン #35 5HP止め中段"),
  },
  {
    id: "combo_36",
    number: 36,
    title: "端最強起き攻め移行",
    startup: "起き攻め",
    notation: "5LP~LP xx DRC > 2LP > 2HP xx 22LP > 2LP xx 214HP > 5HP xx 22MP",
    damage: 1717,
    knockdown: "+5",
    position: "端",
    difficulty: "難",
    description: "画面端での最強起き攻めに移行",
    situationTags: ["起き攻め"],
    videoAsset: comboVideoAsset("yasmine_36", "ヤスミン #36 端最強起き攻め移行"),
  },
  {
    id: "combo_37",
    number: 37,
    title: "スタン後起き攻め移行",
    startup: "スタン・起き攻め",
    notation: "(W! STN)DI > 9jHP > 2HP xx 22LP > 2LP xx 214HP > 5HP xx 22MP",
    damage: 2260,
    knockdown: "+5",
    position: "端",
    difficulty: "難",
    description: "スタン後リーサルがなければこれ！画面端での最強起き攻めに移行",
    situationTags: ["スタン", "起き攻め"],
    videoAsset: comboVideoAsset("yasmine_37", "ヤスミン #37 スタン後起き攻め移行"),
  },
  {
    id: "combo_38",
    number: 38,
    title: "端付近OD起き攻め移行",
    startup: "起き攻め",
    notation: "(CH)2LP > 2MP xx (OD)214PP > 5HP xx 22LP",
    damage: 1640,
    knockdown: "+5",
    position: "端付近",
    difficulty: "中",
    description: "画面端での最強起き攻めに移行可能ではあるがダメージ効率は良くない。",
    situationTags: ["起き攻め"],
    videoAsset: comboVideoAsset("yasmine_38", "ヤスミン #38 端付近OD起き攻め移行"),
  },
  {
    id: "combo_39",
    number: 39,
    title: "+5詐欺飛び",
    startup: "セットプレイ",
    notation: "▲j9HK",
    damage: 0,
    knockdown: "+19",
    position: "端",
    difficulty: "易",
    description: "+5から起き攻め。様子見された場合でも状況有利",
    situationTags: ["セットプレイ"],
    videoAsset: comboVideoAsset("yasmine_39", "ヤスミン #39 +5詐欺飛び"),
  },
  {
    id: "combo_40",
    number: 40,
    title: "+5裏回り確定",
    startup: "セットプレイ",
    notation: "▲j9HK > DR > (PC)5HP > 2HP xx 22LP > 5LK > 22HP > 5HP > 4 > 5HP > 22LP",
    damage: 2920,
    knockdown: "+2",
    position: "端",
    difficulty: "難",
    description: "+5から起き攻め。相手の無敵・SA暴れなどで裏に回った場合のコンボ例",
    situationTags: ["セットプレイ"],
    videoAsset: comboVideoAsset("yasmine_40", "ヤスミン #40 +5裏回り確定"),
  },
  {
    id: "combo_41",
    number: 41,
    title: "+5表落ち確定",
    startup: "セットプレイ",
    notation: "▲j9HK > 214HP > 5HP xx 623HK",
    damage: 2740,
    knockdown: "+19",
    position: "端",
    difficulty: "中",
    description: "+5から起き攻め。投げなどで表落ちの場合のコンボ例",
    situationTags: ["セットプレイ"],
    videoAsset: comboVideoAsset("yasmine_41", "ヤスミン #41 +5表落ち確定"),
  },
  {
    id: "combo_42",
    number: 42,
    title: "+5ジャンプ対応",
    startup: "セットプレイ",
    notation: "j9HK",
    damage: 800,
    knockdown: "+2",
    position: "端",
    difficulty: "易",
    description: "+5から起き攻め。各ジャンプをされた場合",
    situationTags: ["セットプレイ"],
    videoAsset: comboVideoAsset("yasmine_42", "ヤスミン #42 +5ジャンプ対応"),
  },
  {
    id: "combo_43",
    number: 43,
    title: "+5投げ",
    startup: "セットプレイ",
    notation: "投げ",
    damage: 1200,
    knockdown: "+29",
    position: "端",
    difficulty: "易",
    description: "+5から起き攻め。様子見されても他の候補が強い為投げ選択は頻度低めが良い",
    situationTags: ["セットプレイ"],
    videoAsset: comboVideoAsset("yasmine_43", "ヤスミン #43 +5投げ"),
  },
  {
    id: "combo_44",
    number: 44,
    title: "+5ドライブリバーサル対応",
    startup: "セットプレイ",
    notation: "▲j9HK > 裏投げ",
    damage: 2040,
    knockdown: "+24",
    position: "端",
    difficulty: "中",
    description: "+5から起き攻め。ドライブリバーサルされた場合+5でパニッシュカウンターの為2LP > 2HP辺りのコンボでリーサルも狙える",
    situationTags: ["セットプレイ"],
    videoAsset: comboVideoAsset("yasmine_44", "ヤスミン #44 +5ドライブリバーサル対応"),
  },
];

const yasmineCombos: ComboData[] = yasmineCombosRaw.map((combo) => {
  const calculation = calculateGaugeCost(combo.notation);
  return {
    ...combo,
    driveConsumption: calculation.driveConsumption,
    superConsumption: calculation.superConsumption,
    driveGaugeCost: calculation.driveGaugeCost,
  } as ComboData;
});

const yasmineConfig: CharacterConfig = {
  id: "yasmine",
  name: "Yasmine",
  nameJp: "ヤスミン",
  title: "YASMINE COMBO DESK",
  subtitle: "2026年版",
  seoTitle: "SF6 ヤスミン コンボ集｜起き攻め・リーサル・Drive効率検索",
  seoDescription:
    "SF6 ヤスミンのコンボ集。PC DI、差し返し、壁やられ、スタン、起き攻めルートを動画付きで整理。",
  beginnerComboIds: [6, 17, 2],
  beginnerSteps: [
    {
      comboId: 6,
      filterPurpose: "起き攻め",
      note: "ドライブラッシュで先制攻撃を仕掛けバヤニ・モードを溜める技を当て、打撃・投げ・シミーの攻め継続へつなげる",
    },
    {
      comboId: 17,
      filterPurpose: "運び",
      candidateComboIds: [17, 18, 19, 20, 21, 22, 28, 31, 32, 33],
      note: "バヤニ・モードを溜めた時のコンボ・連携を覚える。",
    },
    {
      comboId: 2,
      filterPurpose: "(PC)DI",
      candidateComboIds: [2, 1, 4, 5, 10, 11, 12, 13, 14],
      note: "インパクト・スタン・壁やられ・無敵ガード後などの確定状況を覚える",
    },
  ],

  colors: {
    primary: "#14b8a6",
    accent: "#f97316",
    background: "linear-gradient(135deg, #061312 0%, #17201d 50%, #100d0a 100%)",
  },

  description:
    "ヤスミンのコンボを始動・位置・ゲージ消費・起き攻め有利で比較できるレポートです。",

  comboTheoryHeading: "ヤスミンのコンボ方針",

  comboTheory:
    "ヤスミンはバヤニ・モードを溜めながら起き攻めへつなぐ展開と、PC DI・壁やられ・スタン時の位置別判断が重要。ノーゲージ安定ルートとDRC起き攻めを使い分け、投げ・シミー・持続当ての状況を作ることが勝ち筋になります。",

  comboTheoryDetail:
    "まずはインパクト返しの入れ替え、壁やられのお手軽コンボ、下段DRCからの攻め継続を軸に覚え、慣れてきたら#8の+38持続当てや#9の+43密着起き攻め、#10の壁スタン最大へ広げます。",

  patchFindings: [
    {
      date: "2026-08-04",
      change: "ヤスミン実用ルート追加",
      comboImpact: "PC DI、差し返し、壁やられ、スタン、起き攻めの初期コンボカードを追加。",
      confidence: "中",
    },
  ],

  combos: yasmineCombos,

  filterOptions: {
    positions: ["すべて", "どこでも", "端", "端付近"],
    purposes: [
      "すべて",
      "温存",
      "起き攻め",
      "入れ替え",
      "運び",
      "リーサル",
      "差し返し",
      "セットプレイ",
      "(PC)DI",
      "壁やられ",
      "スタン",
      "その他",
    ],
    situationTags: [
      "温存",
      "起き攻め",
      "入れ替え",
      "運び",
      "リーサル",
      "差し返し",
      "セットプレイ",
      "(PC)DI",
      "壁やられ",
      "スタン",
      "その他",
    ],
  },
};

registerCharacter(yasmineConfig);

export default yasmineConfig;
