import { type CharacterConfig, registerCharacter } from "../characterConfig";
import { calculateGaugeCost, comboVideoAsset, type ComboData } from "../comboData";

const yasmineCombosRaw: Omit<ComboData, "driveConsumption" | "superConsumption">[] = [
  {
    id: "combo_1",
    number: 1,
    title: "PC DI入れ替え",
    startup: "その他",
    notation: "(PC)DI > 236LK~P > 5HP xx 421HK",
    damage: 2660,
    knockdown: "+19",
    position: "端付近",
    difficulty: "易",
    description: "インパクト返し・無敵など入れ替えコンボ",
    situationTags: ["その他"],
    videoAsset: comboVideoAsset("yasmine_01", "ヤスミン #01 PC DI入れ替え"),
  },
  {
    id: "combo_2",
    number: 2,
    title: "PC DI運び",
    startup: "(PC)DI",
    notation: "(PC)DI > jHK >  DR > 2MP xx 214HP > 5HP xx 623HK",
    damage: 3175,
    knockdown: "+19",
    position: "どこでも",
    difficulty: "中",
    description: "インパクト返し運び・ダメージも含めリーサル以外はこれでOK",
    situationTags: ["(PC)DI", "運び"],
    videoAsset: comboVideoAsset("yasmine_02", "ヤスミン #02 PC DI運び"),
  },
  {
    id: "combo_3",
    number: 3,
    title: "大K差し返し",
    startup: "差し返し",
    notation: "(PC)HK >  DR > 2MP xx 214HP > 5HP xx 623HK",
    damage: 2535,
    knockdown: "+19",
    position: "どこでも",
    difficulty: "中",
    description: "大Kカウンター時は運び・ダメージとこれが安定",
    situationTags: ["差し返し", "運び"],
    videoAsset: comboVideoAsset("yasmine_03", "ヤスミン #03 大K差し返し"),
  },
  {
    id: "combo_4",
    number: 4,
    title: "DI壁やられノーゲージ",
    startup: "壁やられ",
    notation: "(W!)DI > 2HP xx 214MP > 5HP xx 623HK",
    damage: 2501,
    knockdown: "+19",
    position: "端付近",
    difficulty: "易",
    description: "ノーゲージお手軽コンボ",
    situationTags: ["壁やられ"],
    videoAsset: comboVideoAsset("yasmine_04", "ヤスミン #04 DI壁やられノーゲージ"),
  },
  {
    id: "combo_5",
    number: 5,
    title: "壁スタン汎用",
    startup: "スタン",
    notation: "(W! STN)DI > 66 > 7j > 22HP > 5HK > 214HP > 5HP xx 623HK",
    damage: 2410,
    knockdown: "+19",
    position: "端付近",
    difficulty: "中",
    description: "壁スタンであればどこからでもOK",
    situationTags: ["スタン"],
    videoAsset: comboVideoAsset("yasmine_05", "ヤスミン #05 壁スタン汎用"),
  },
  {
    id: "combo_6",
    number: 6,
    title: "下段DRC起き攻め",
    startup: "起き攻め",
    notation: "2MK xx  DRC > 2MP > 2HP xx 214MP",
    damage: 1941,
    knockdown: "+2",
    position: "どこでも",
    difficulty: "中",
    description: "バヤニ・モードを溜めて攻め継続・投げorシミーが可能",
    situationTags: ["起き攻め"],
    videoAsset: comboVideoAsset("yasmine_06", "ヤスミン #06 下段DRC起き攻め"),
  },
  {
    id: "combo_7",
    number: 7,
    title: "シミー後セットプレイ",
    startup: "セットプレイ",
    notation: "2MP > 2HP xx 236HP~6P >  DR > 2MP xx 214HP > 5HP xx 623HK",
    damage: 3659,
    knockdown: "+19",
    position: "どこでも",
    difficulty: "中",
    description: "#6のシミー後に狙うコンボの一例",
    situationTags: ["セットプレイ"],
    videoAsset: comboVideoAsset("yasmine_07", "ヤスミン #07 シミー後セットプレイ"),
  },
  {
    id: "combo_8",
    number: 8,
    title: "+38持続当て",
    startup: "起き攻め",
    notation: "2MK xx  DRC > 2MP > 5MP~MP xx 236MP~6MP",
    damage: 1752,
    knockdown: "+38",
    position: "どこでも",
    difficulty: "中",
    description: "バヤニ・モードを溜めて攻め継続。5LPフレーム消費6MPで持続当て+5",
    situationTags: ["起き攻め"],
    videoAsset: comboVideoAsset("yasmine_08", "ヤスミン #08 +38持続当て"),
  },
  {
    id: "combo_9",
    number: 9,
    title: "+43密着起き攻め",
    startup: "起き攻め",
    notation: "DR > 2MP > 2HP xx (OD)22PP > LK > 22HP > 2HK > 214MP",
    damage: 2910,
    knockdown: "+43",
    position: "どこでも",
    difficulty: "中",
    description: "バヤニ・モードを溜めて攻め継続。前ダッシュx2で+5密着",
    situationTags: ["起き攻め"],
    videoAsset: comboVideoAsset("yasmine_09", "ヤスミン #09 +43密着起き攻め"),
  },
  {
    id: "combo_10",
    number: 10,
    title: "壁スタンノーゲージ最大",
    startup: "スタン",
    notation: "(W! STN)DI > 44 > 44 > 66 > 8jHK > 2HP xx 22HP > 2MP > 214HP > 5HP xx 623HK",
    damage: 2510,
    knockdown: "+20",
    position: "端付近",
    difficulty: "難",
    description: "密着時の壁スタン後ノーゲージ最大",
    situationTags: ["スタン"],
    videoAsset: comboVideoAsset("yasmine_10", "ヤスミン #10 壁スタンノーゲージ最大"),
  },
  {
    id: "combo_11",
    number: 11,
    title: "マニアック入れ替え",
    startup: "入れ替え",
    notation: "DR > (PC)5HP > 2HP xx 22LP > LK > 22HP > 5HP > 66 > 421HK",
    damage: 3100,
    knockdown: "+19",
    position: "端付近",
    difficulty: "難",
    description: "マニアックな入れ替えコンボ",
    situationTags: ["その他"],
    videoAsset: comboVideoAsset("yasmine_11", "ヤスミン #11 マニアック入れ替え"),
  },
  {
    id: "combo_12",
    number: 12,
    title: "PC 5HP運び",
    startup: "運び",
    notation: "DR > (PC)5HP > 2HP xx 22LP > LK xx 214HP > 5HP xx 623HK",
    damage: 3510,
    knockdown: "+20",
    position: "どこでも",
    difficulty: "中",
    description: "SAやOD昇龍などガード時に選択するコンボ",
    situationTags: ["運び"],
    videoAsset: comboVideoAsset("yasmine_12", "ヤスミン #12 PC 5HP運び"),
  },
  {
    id: "combo_13",
    number: 13,
    title: "端PC 2HP高火力",
    startup: "その他",
    notation: "DR > (PC)2HP > 2HP xx 22MP > 2MP xx 214HP > 5HP xx 623HK",
    damage: 3690,
    knockdown: "+19",
    position: "端",
    difficulty: "難",
    description: "#12よりもダメージ増。意識が高い人向け。",
    situationTags: ["その他"],
    videoAsset: comboVideoAsset("yasmine_13", "ヤスミン #13 端PC 2HP高火力"),
  },
  {
    id: "combo_14",
    number: 14,
    title: "端ODリーサル",
    startup: "その他・リーサル",
    notation: "DR > (PC)5HP > 5HP xx (OD)22LPHP > 2MP > 8jMP > 214MP > 5HP xx 623HK",
    damage: 3900,
    knockdown: "+19",
    position: "端",
    difficulty: "難",
    description: "#13よりもダメージ増。意識が高い人向け。",
    situationTags: ["その他", "リーサル"],
    videoAsset: comboVideoAsset("yasmine_14", "ヤスミン #14 端ODリーサル"),
  },
  {
    id: "combo_15",
    number: 15,
    title: "下段DR密着攻め",
    startup: "起き攻め",
    notation: "DR > 2LK > 2MP xx 214MP",
    damage: 1450,
    knockdown: "+2",
    position: "どこでも",
    difficulty: "易",
    description: "下段からの密着攻め持続用",
    situationTags: ["起き攻め"],
    videoAsset: comboVideoAsset("yasmine_15", "ヤスミン #15 下段DR密着攻め"),
  },
  {
    id: "combo_16",
    number: 16,
    title: "中攻撃DR密着攻め",
    startup: "起き攻め",
    notation: "DR > 2MP > 2HP xx 214MP",
    damage: 2280,
    knockdown: "+2",
    position: "どこでも",
    difficulty: "易",
    description: "攻めの起点からの密着攻め持続用",
    situationTags: ["起き攻め"],
    videoAsset: comboVideoAsset("yasmine_16", "ヤスミン #16 中攻撃DR密着攻め"),
  },
  {
    id: "combo_17",
    number: 17,
    title: "バヤニ基本運び",
    startup: "運び",
    notation: "DR > 2MP > 2HP xx 236HP~6P > DR > 2MP xx 214HP > 5HP xx 623HK",
    damage: 3479,
    knockdown: "+19",
    position: "どこでも",
    difficulty: "中",
    stock: "あり",
    description: "バヤニ・モード時の基本コンボ。画面端付近の場合途中2HP xx 214MPに変更でダメージ増",
    situationTags: ["運び"],
    videoAsset: comboVideoAsset("yasmine_17", "ヤスミン #17 バヤニ基本運び"),
  },
  {
    id: "combo_18",
    number: 18,
    title: "下段バヤニ基本運び",
    startup: "運び",
    notation: "DR > 2LK > 2MP xx 236HP~6P > DR > 2MP xx 214HP > 5HP xx 623HK",
    damage: 2360,
    knockdown: "+19",
    position: "どこでも",
    difficulty: "中",
    stock: "あり",
    description: "下段始動バヤニ・モード時の基本コンボ。画面端付近の場合途中2HP xx 214MPに変更でダメージ増",
    situationTags: ["運び"],
    videoAsset: comboVideoAsset("yasmine_18", "ヤスミン #18 下段バヤニ基本運び"),
  },
  {
    id: "combo_19",
    number: 19,
    title: "バヤニSA2高火力",
    startup: "リーサル",
    notation: "DR > 2MP > 2HP xx (OD)236PP~6P xx SA2 > 214HP > (OD)236PP~6P",
    damage: 4780,
    knockdown: "+47",
    position: "どこでも",
    difficulty: "難",
    stock: "あり",
    description: "バヤニ・モードSA2高火力コンボ。",
    situationTags: ["リーサル"],
    videoAsset: comboVideoAsset("yasmine_19", "ヤスミン #19 バヤニSA2高火力"),
  },
  {
    id: "combo_20",
    number: 20,
    title: "端空中5HP投げ",
    startup: "セットプレイ",
    notation: "（空中） > 5HP xx 22MP > 投げ",
    damage: 1200,
    knockdown: "+29",
    position: "端",
    difficulty: "易",
    stock: "あり",
    description: "#17#18他、画面端で空中5HP後の起き攻め重視はこれ",
    situationTags: ["セットプレイ"],
    videoAsset: comboVideoAsset("yasmine_20", "ヤスミン #20 端空中5HP投げ"),
  },
  {
    id: "combo_21",
    number: 21,
    title: "端空中5HP SA3",
    startup: "セットプレイ",
    notation: "（空中） > 5HP xx 22MP > 2MP xx 236LP > 5HP xx (OD)236PP~6P > SA3",
    damage: 4640,
    knockdown: "+42",
    position: "端",
    difficulty: "難",
    stock: "あり",
    description: "#17#18他、画面端で空中5HP後の起き攻め（2MPヒット時のレシピ）",
    situationTags: ["セットプレイ"],
    videoAsset: comboVideoAsset("yasmine_21", "ヤスミン #21 端空中5HP SA3"),
  },
  {
    id: "combo_22",
    number: 22,
    title: "端空中5HP二段ヒット",
    startup: "セットプレイ",
    notation: "（空中） > 5HP xx 22MP > 2MP xx 236LP > 2MP xx 236HP~P >  DR > 2HP xx 214MP > 5HP xx 623HK",
    damage: 3322,
    knockdown: "+19",
    position: "端",
    difficulty: "難",
    stock: "あり",
    description: "#17#18他、画面端で空中5HP後の起き攻め（2回目2MPヒット時のレシピ）",
    situationTags: ["セットプレイ"],
    videoAsset: comboVideoAsset("yasmine_22", "ヤスミン #22 端空中5HP二段ヒット"),
  },
];

const yasmineCombos: ComboData[] = yasmineCombosRaw.map((combo) => {
  const calculation = calculateGaugeCost(combo.notation);
  return {
    ...combo,
    driveConsumption: calculation.driveConsumption,
    superConsumption: calculation.superConsumption,
    driveGaugeCost: calculation.driveGaugeCost,
  } as ComboData;
});

const yasmineConfig: CharacterConfig = {
  id: "yasmine",
  name: "Yasmine",
  nameJp: "ヤスミン",
  title: "YASMINE COMBO DESK",
  subtitle: "2026年版",
  seoTitle: "SF6 ヤスミン コンボ集｜起き攻め・リーサル・Drive効率検索",
  seoDescription:
    "SF6 ヤスミンのコンボ集。PC DI、差し返し、壁やられ、スタン、起き攻めルートを動画付きで整理。",
  beginnerComboIds: [6, 17, 2],
  beginnerSteps: [
    {
      comboId: 6,
      filterPurpose: "起き攻め",
      note: "ドライブラッシュで先制攻撃を仕掛けバヤニ・モードを溜める技を当て、打撃・投げ・シミーの攻め継続へつなげる",
    },
    {
      comboId: 17,
      filterPurpose: "運び",
      candidateComboIds: [17, 18, 19, 20, 21, 22],
      note: "バヤニ・モードを溜めた時のコンボ・連携を覚える。",
    },
    {
      comboId: 2,
      filterPurpose: "(PC)DI",
      candidateComboIds: [2, 1, 4, 5, 10, 11, 12, 13, 14],
      note: "インパクト・スタン・壁やられ・無敵ガード後などの確定状況を覚える",
    },
  ],

  colors: {
    primary: "#14b8a6",
    accent: "#f97316",
    background: "linear-gradient(135deg, #061312 0%, #17201d 50%, #100d0a 100%)",
  },

  description:
    "ヤスミンのコンボを始動・位置・ゲージ消費・起き攻め有利で比較できるレポートです。",

  comboTheoryHeading: "ヤスミンのコンボ方針",

  comboTheory:
    "ヤスミンはバヤニ・モードを溜めながら起き攻めへつなぐ展開と、PC DI・壁やられ・スタン時の位置別判断が重要。ノーゲージ安定ルートとDRC起き攻めを使い分け、投げ・シミー・持続当ての状況を作ることが勝ち筋になります。",

  comboTheoryDetail:
    "まずはインパクト返しの入れ替え、壁やられのお手軽コンボ、下段DRCからの攻め継続を軸に覚え、慣れてきたら#8の+38持続当てや#9の+43密着起き攻め、#10の壁スタン最大へ広げます。",

  patchFindings: [
    {
      date: "2026-08-04",
      change: "ヤスミン実用ルート追加",
      comboImpact: "PC DI、差し返し、壁やられ、スタン、起き攻めの初期コンボカードを追加。",
      confidence: "中",
    },
  ],

  combos: yasmineCombos,

  filterOptions: {
    positions: ["すべて", "どこでも", "端", "端付近"],
    purposes: [
      "すべて",
      "温存",
      "起き攻め",
      "入れ替え",
      "運び",
      "リーサル",
      "差し返し",
      "セットプレイ",
      "(PC)DI",
      "壁やられ",
      "スタン",
      "その他",
    ],
    situationTags: [
      "温存",
      "起き攻め",
      "入れ替え",
      "運び",
      "リーサル",
      "差し返し",
      "セットプレイ",
      "(PC)DI",
      "壁やられ",
      "スタン",
      "その他",
    ],
  },
};

registerCharacter(yasmineConfig);

export default yasmineConfig;
